spring:
  cloud:
    stream:
      rabbit:
        binder:
          nodes: localhost
        bindings:
          purchase-created:
            consumer:1
            queueNameGroupOnly: true
      bindings:
        purchase-created:
          destination: my-exchange
          group: my-queue
